### ISSUE TITLE
FEATURE REQUEST: Add "Build Status" to Repositories tab

### ISSUE THREAD

**Issue by oneezy** [Yaowenjie/travis-github-chrome-extension#9]
Currently, the extension adds the "Build Status" badge to "Overview" tab. 

It would be a helpful feature to also add the "Build Status" badge to the "Repositories" tab.

Here's a screen shot of the issue:

![image](https://cloud.githubusercontent.com/assets/7369575/21082829/2f3d3ad0-bfa9-11e6-81a9-44e068649483.png)

**Comment by Yaowenjie** [comment]
@oneezy  Thanks for your request, it is indeed an issue. Cause it works before github layout change. Anyway, I'll fix it if I get time to look into it. BTW, any good pull requests are welcome. :)

**Comment by oneezy** [comment]
Oh I see,, I wonder when they did that? 

Anyways, Thanks for the extension!..It's a good one. Keep up the great work!

**Comment by Yaowenjie** [comment]
Hey @oneezy, I just fixed the issue (or in other word, added this feature), and added the Travis-CI build status badge on stars tab as well. As below:
<img width="1014" alt="screen shot 2016-12-17 at 4 50 47 pm" src="https://cloud.githubusercontent.com/assets/9637652/21285671/1050ed1c-c47a-11e6-90ab-86e47b391474.png">
<img width="1059" alt="screen shot 2016-12-17 at 4 51 07 pm" src="https://cloud.githubusercontent.com/assets/9637652/21285672/10b04898-c47a-11e6-9ff4-3496fb5ab5e8.png">

And I just published a [new version one(2.0.11)](https://chrome.google.com/webstore/detail/github-travis-stat/ekkfhiophiaakmeppcnkblpbbjlnlnmh) on chrome store. However, you'l find an interesting thing: if you click the 'Repositories' tab from 'Overview' tab, you'll not see the badges, otherwise you refresh the page. I already created a [new issue](https://github.com/Yaowenjie/travis-github-chrome-extension/issues/13) to track it.

BTW, the build status chart on one repo can be collapsed by click chart header now. 

At last, thanks for your feedback, please feel free to give it more. Hope you enjoy it!

**Comment by oneezy** [comment]
Ok, that's awesome! 
I'll be sure to test it out soon. 

As for issue #13 , 
It seems like that's a pretty common problem w/ extensions I've seen. The same problem affects one of my personal extensions (I've halfway fixed it but still have some issues).

One thing that's a tiny small annoyance is the `<canvas>` text being blurry in the chart. I've never messed around w/ canvas before but I might have a go at helping out w/ it and/or throwing some more ideas out towards it 😁
